// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgh_ZBzIfBI60BjGeTktGAwGGUch8DULs',
    appId: '1:784922252329:web:02f6acf42bfb5ca3d93838',
    messagingSenderId: '784922252329',
    projectId: 'basic-firebaselogin',
    authDomain: 'basic-firebaselogin.firebaseapp.com',
    storageBucket: 'basic-firebaselogin.firebasestorage.app',
    measurementId: 'G-RZC31MDYVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8tAmJI4qphYwyHLcNEr3q3L7Mar9_Kpo',
    appId: '1:784922252329:android:cbadf6478b5865d3d93838',
    messagingSenderId: '784922252329',
    projectId: 'basic-firebaselogin',
    storageBucket: 'basic-firebaselogin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkDlWeeOa_07M0Iav2GF54Pc-tvTH2tqM',
    appId: '1:784922252329:ios:2c92f46a85345547d93838',
    messagingSenderId: '784922252329',
    projectId: 'basic-firebaselogin',
    storageBucket: 'basic-firebaselogin.firebasestorage.app',
    iosBundleId: 'com.example.basicFirebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkDlWeeOa_07M0Iav2GF54Pc-tvTH2tqM',
    appId: '1:784922252329:ios:2c92f46a85345547d93838',
    messagingSenderId: '784922252329',
    projectId: 'basic-firebaselogin',
    storageBucket: 'basic-firebaselogin.firebasestorage.app',
    iosBundleId: 'com.example.basicFirebaseLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgh_ZBzIfBI60BjGeTktGAwGGUch8DULs',
    appId: '1:784922252329:web:790c510b3f1b0babd93838',
    messagingSenderId: '784922252329',
    projectId: 'basic-firebaselogin',
    authDomain: 'basic-firebaselogin.firebaseapp.com',
    storageBucket: 'basic-firebaselogin.firebasestorage.app',
    measurementId: 'G-XHG8MDDDXQ',
  );
}
